from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]

STATIC_MODEL_PATH = PROJECT_ROOT / "models" / "checkpoints" / "static_best_model.joblib"
STATIC_MODEL_META_PATH = (
    PROJECT_ROOT / "models" / "checkpoints" / "static_best_model_meta.json"
)
HAND_MODEL_PATH = PROJECT_ROOT / "models" / "hand_landmarker.task"

ICON_DIR = PROJECT_ROOT / "assets" / "gesture_icons"

ACTIVE_LABEL = "open_palm"
LOCK_LABEL = "fist"
MOVE_LABEL = "point"
CLICK_LABEL = "pinch"
DYNAMIC_GATE_LABEL = "two_fingers"

SMOOTHING_WINDOW = 5
SMOOTHING_MIN_VOTES = 3
SECONDARY_SMOOTHING_WINDOW = 4
SECONDARY_SMOOTHING_MIN_VOTES = 2
NO_HAND_RESET_FRAMES = 6

MOUSE_SMOOTHING = 0.1
CLICK_COOLDOWN_SEC = 0.60
PINCH_TOUCH_THRESHOLD = 0.055
PINCH_RELEASE_THRESHOLD = 0.075
MODE_SWITCH_COOLDOWN_SEC = 0.80
MOVE_ONLY_WHEN_ACTIVE = True
MOVE_DEADZONE = 0.0005
POINTER_MARGIN_X = 0.25
POINTER_MARGIN_Y = 0.25
POINT_CURSOR_OFFSET_X = 0.0
POINT_CURSOR_OFFSET_Y = 0.0
PRIMARY_SWITCH_MAX_DISTANCE = 0.35

DYNAMIC_COOLDOWN_SEC = 0.65
NAVIGATION_ACTION_COOLDOWN_SEC = 3.0
POSE_BUFFER_SIZE = 12
POSE_MIN_FRAMES = 5
POSE_MAX_MOTION = 0.040
ORIENT_VERTICAL_RATIO = 1.22
ORIENT_HORIZONTAL_RATIO = 1.18
UP_SPREAD_RATIO_MIN = 0.22
DOWN_SPREAD_RATIO_MAX = 0.17
SCROLL_AMOUNT = 180

CAMERA_WIDTH = 1280
CAMERA_HEIGHT = 720
CAMERA_FPS = 60

PREVIEW_BASE_WIDTH = 640
PREVIEW_BASE_HEIGHT = 360
GUIDE_PANEL_WIDTH = 480

PREVIEW_MARGIN_RIGHT = 18
PREVIEW_MARGIN_BOTTOM = 58
PREVIEW_WINDOW_NAME = "Hand Gesture Control"

DRAW_MOUSE_PREVIEW = True
DRAW_LANDMARKS_ON_PREVIEW = True
DRAW_DEBUG_PANEL = False
RENDER_EVERY_N_FRAMES = 1

FIXED_PREVIEW_WINDOW = True
PREVIEW_TOPMOST = True
PREVIEW_COMPACT_RENDER = False
SKIP_PREVIEW_WHEN_MINIMIZED = False
MIN_RENDER_WINDOW_SIZE = 64
PREVIEW_SCALE_DEFAULT = 1.0
PREVIEW_SCALE_MIN = 0.45
PREVIEW_SCALE_MAX = 1.80
PREVIEW_SCALE_STEP = 0.10
PREVIEW_PIN_TO_BOTTOM_RIGHT = True

VERBOSE_DYNAMIC_LOG = False
LOG_COOLDOWN_SEC = 0.35
ACTION_HISTORY_SIZE = 6
EPS = 1e-6
